[package]
name = "metrics"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "metrics"
path = "src/main.rs"

[dependencies]
syn = { version = "2", features = ["full", "parsing", "visit"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
walkdir = "2"
